
package br.gov.in.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servicoINPortType", targetNamespace = "http://xfire.ws.incom")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicoINPortType {


    /**
     * 
     * @param dados
     * @return
     *     returns br.gov.in.ws.RespostaConsultaAcompanhamentoOficio
     */
    @WebMethod(operationName = "ConsultaEstadoMateria")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaEstadoMateria", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaEstadoMateria")
    @ResponseWrapper(localName = "ConsultaEstadoMateriaResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaEstadoMateriaResponse")
    public RespostaConsultaAcompanhamentoOficio consultaEstadoMateria(
        @WebParam(name = "dados", targetNamespace = "http://xfire.ws.incom")
        DadosConsultaEstadoMateria dados);

    /**
     * 
     * @param cpf
     * @return
     *     returns br.gov.in.ws.RespostaConsultaFormasPagamento
     */
    @WebMethod(operationName = "ConsultaFormasPagamento")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaFormasPagamento", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaFormasPagamento")
    @ResponseWrapper(localName = "ConsultaFormasPagamentoResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaFormasPagamentoResponse")
    public RespostaConsultaFormasPagamento consultaFormasPagamento(
        @WebParam(name = "CPF", targetNamespace = "http://xfire.ws.incom")
        String cpf);

    /**
     * 
     * @param idTransacao
     * @return
     *     returns br.gov.in.ws.RespostaConsultaIDTransacao
     */
    @WebMethod(operationName = "ConsultaIDTransacao")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaIDTransacao", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaIDTransacao")
    @ResponseWrapper(localName = "ConsultaIDTransacaoResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaIDTransacaoResponse")
    public RespostaConsultaIDTransacao consultaIDTransacao(
        @WebParam(name = "IDTransacao", targetNamespace = "http://xfire.ws.incom")
        String idTransacao);

    /**
     * 
     * @param cpf
     * @return
     *     returns br.gov.in.ws.RespostaConsultaJornais
     */
    @WebMethod(operationName = "ConsultaJornais")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaJornais", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaJornais")
    @ResponseWrapper(localName = "ConsultaJornaisResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaJornaisResponse")
    public RespostaConsultaJornais consultaJornais(
        @WebParam(name = "CPF", targetNamespace = "http://xfire.ws.incom")
        String cpf);

    /**
     * 
     * @param identificadorJornal
     * @return
     *     returns br.gov.in.ws.RespostaConsultaNormas
     */
    @WebMethod(operationName = "ConsultaNormas")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaNormas", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaNormas")
    @ResponseWrapper(localName = "ConsultaNormasResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaNormasResponse")
    public RespostaConsultaNormas consultaNormas(
        @WebParam(name = "IdentificadorJornal", targetNamespace = "http://xfire.ws.incom")
        int identificadorJornal);

    /**
     * 
     * @param dados
     * @return
     *     returns br.gov.in.ws.RespostaConsultaAcompanhamentoOficio
     */
    @WebMethod(operationName = "ConsultaAcompanhamentoOficio")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaAcompanhamentoOficio", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaAcompanhamentoOficio")
    @ResponseWrapper(localName = "ConsultaAcompanhamentoOficioResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaAcompanhamentoOficioResponse")
    public RespostaConsultaAcompanhamentoOficio consultaAcompanhamentoOficio(
        @WebParam(name = "dados", targetNamespace = "http://xfire.ws.incom")
        DadosConsultaAcompanhamentoOficio dados);

    /**
     * 
     * @param dados
     * @return
     *     returns br.gov.in.ws.ValidacaoPreview
     */
    @WebMethod(operationName = "OficioPreview")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "OficioPreview", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.OficioPreview")
    @ResponseWrapper(localName = "OficioPreviewResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.OficioPreviewResponse")
    public ValidacaoPreview oficioPreview(
        @WebParam(name = "dados", targetNamespace = "http://xfire.ws.incom")
        DadosOficioPreview dados);

    /**
     * 
     * @return
     *     returns br.gov.in.ws.RespostaConsultaTodosFeriado
     */
    @WebMethod(operationName = "ConsultaTodosFeriado")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaTodosFeriado", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaTodosFeriado")
    @ResponseWrapper(localName = "ConsultaTodosFeriadoResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaTodosFeriadoResponse")
    public RespostaConsultaTodosFeriado consultaTodosFeriado();

    /**
     * 
     * @param dados
     * @return
     *     returns br.gov.in.ws.RespostaSustaMateria
     */
    @WebMethod(operationName = "SustaMateria")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "SustaMateria", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.SustaMateria")
    @ResponseWrapper(localName = "SustaMateriaResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.SustaMateriaResponse")
    public RespostaSustaMateria sustaMateria(
        @WebParam(name = "dados", targetNamespace = "http://xfire.ws.incom")
        DadosSustaMateria dados);

    /**
     * 
     * @param dados
     * @return
     *     returns br.gov.in.ws.ValidacaoConfirmacao
     */
    @WebMethod(operationName = "OficioConfirmacao")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "OficioConfirmacao", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.OficioConfirmacao")
    @ResponseWrapper(localName = "OficioConfirmacaoResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.OficioConfirmacaoResponse")
    public ValidacaoConfirmacao oficioConfirmacao(
        @WebParam(name = "dados", targetNamespace = "http://xfire.ws.incom")
        DadosOficioConfirmacao dados);

    /**
     * 
     * @param cpf
     * @return
     *     returns br.gov.in.ws.RespostaConsultaOrgaosPermitidos
     */
    @WebMethod(operationName = "ConsultaOrgaosPermitidos")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaOrgaosPermitidos", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaOrgaosPermitidos")
    @ResponseWrapper(localName = "ConsultaOrgaosPermitidosResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaOrgaosPermitidosResponse")
    public RespostaConsultaOrgaosPermitidos consultaOrgaosPermitidos(
        @WebParam(name = "CPF", targetNamespace = "http://xfire.ws.incom")
        String cpf);

    /**
     * 
     * @return
     *     returns br.gov.in.ws.RespostaConsultaTodosMotivosIsencao
     */
    @WebMethod(operationName = "ConsultaTodosMotivosIsencao")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaTodosMotivosIsencao", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaTodosMotivosIsencao")
    @ResponseWrapper(localName = "ConsultaTodosMotivosIsencaoResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaTodosMotivosIsencaoResponse")
    public RespostaConsultaTodosMotivosIsencao consultaTodosMotivosIsencao();

    /**
     * 
     * @param dados
     * @return
     *     returns br.gov.in.ws.RespostaReagendaOficio
     */
    @WebMethod(operationName = "ReagendaOficio")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ReagendaOficio", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ReagendaOficio")
    @ResponseWrapper(localName = "ReagendaOficioResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ReagendaOficioResponse")
    public RespostaReagendaOficio reagendaOficio(
        @WebParam(name = "dados", targetNamespace = "http://xfire.ws.incom")
        DadosReagendaOficio dados);

    /**
     * 
     * @return
     *     returns br.gov.in.ws.RespostaConsultaTodosOrgaosPermitidos
     */
    @WebMethod(operationName = "ConsultaTodosOrgaosPermitidos")
    @WebResult(name = "out", targetNamespace = "http://xfire.ws.incom")
    @RequestWrapper(localName = "ConsultaTodosOrgaosPermitidos", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaTodosOrgaosPermitidos")
    @ResponseWrapper(localName = "ConsultaTodosOrgaosPermitidosResponse", targetNamespace = "http://xfire.ws.incom", className = "br.gov.in.ws.ConsultaTodosOrgaosPermitidosResponse")
    public RespostaConsultaTodosOrgaosPermitidos consultaTodosOrgaosPermitidos();

}
