
package br.gov.in.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "servicoIN", targetNamespace = "http://xfire.ws.incom", wsdlLocation = "https://wsincom.in.gov.br/services/servicoIN?wsdl")
@HandlerChain(file="handler.xml")
public class ServicoIN
    extends Service
{

    private final static URL SERVICOIN_WSDL_LOCATION;
    private final static WebServiceException SERVICOIN_EXCEPTION;
    private final static QName SERVICOIN_QNAME = new QName("http://xfire.ws.incom", "servicoIN");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://wsincom.in.gov.br/services/servicoIN?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICOIN_WSDL_LOCATION = url;
        SERVICOIN_EXCEPTION = e;
    }

    public ServicoIN() {
        super(__getWsdlLocation(), SERVICOIN_QNAME);
    }

    public ServicoIN(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICOIN_QNAME, features);
    }

    public ServicoIN(URL wsdlLocation) {
        super(wsdlLocation, SERVICOIN_QNAME);
    }

    public ServicoIN(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICOIN_QNAME, features);
    }

    public ServicoIN(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoIN(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicoINPortType
     */
    @WebEndpoint(name = "servicoINHttpPort")
    public ServicoINPortType getServicoINHttpPort() {
        return super.getPort(new QName("http://xfire.ws.incom", "servicoINHttpPort"), ServicoINPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoINPortType
     */
    @WebEndpoint(name = "servicoINHttpPort")
    public ServicoINPortType getServicoINHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xfire.ws.incom", "servicoINHttpPort"), ServicoINPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICOIN_EXCEPTION!= null) {
            throw SERVICOIN_EXCEPTION;
        }
        return SERVICOIN_WSDL_LOCATION;
    }

}
